Doctor.create(
  name: "测试医生",
  gender: "0",
  home_address: "中南路",
  id_card_front: nil,
  good_at: "外科",
  write_uid: nil,
  license_back_media_id: "",
  hospital: "省中医院",
  license_front: nil,
  id_card_front_media_id: "",
  date_of_birth: Time.zone.now - 20.years,
  work_address: "珞瑜路",
  job_title: nil,
  mobile_phone: "18071133633",
  license_front_media_id: "",
  id_card_back_media_id: "",
  id_card_back: nil,
  remark: "",
  avatar: nil,
  license_back: nil,
  age: nil,
  id_card_num: ""
)
