Symptom.create(name: '咳嗽', detail: '伴随发热37.5℃～39℃')
Symptom.create(name: '咳嗽', detail: '伴随发热39℃以上')
Symptom.create(name: '咳嗽', detail: '每天咳嗽5次以上')
Symptom.create(name: '咳嗽', detail: '有黄痰')
Symptom.create(name: '咳嗽', detail: '咳嗽频率1-2秒/次')
Symptom.create(name: '咳嗽', detail: '轻咳')
Symptom.create(name: '咳嗽', detail: '有白痰')
Symptom.create(name: '咳嗽', detail: '有可疑异物')
Symptom.create(name: '咳嗽', detail: '有固定诱发物')
Symptom.create(name: '咳嗽', detail: '每天咳嗽1～2次')
Symptom.create(name: '咳嗽', detail: '咳嗽频率2-3秒/次')
Symptom.create(name: '咳嗽', detail: '有呼吸困难／加快')
Symptom.create(name: '咳嗽', detail: '单咳')
Symptom.create(name: '咳嗽', detail: '呛咳')
Symptom.create(name: '咳嗽', detail: '每天咳嗽3～5次')
Symptom.create(name: '咳嗽', detail: '伴随发热37.5℃以下')
Symptom.create(name: '咳嗽', detail: '犬吠样咳')
Symptom.create(name: '咳嗽', detail: '咳喘')
Symptom.create(name: '咳嗽', detail: '在上呼吸道感染恢复期')


Symptom.create(name: '腹泻', detail: '腹泻至今小于24小时')
Symptom.create(name: '腹泻', detail: '大便稀糊状')
Symptom.create(name: '腹泻', detail: '腹泻至今4-5天')
Symptom.create(name: '腹泻', detail: '大便肉眼能看到脓血')
Symptom.create(name: '腹泻', detail: '每日大便四次以上')
Symptom.create(name: '腹泻', detail: '精神烦躁')
Symptom.create(name: '腹泻', detail: '伴随呕吐')
Symptom.create(name: '腹泻', detail: '腹泻至今5天以上')
Symptom.create(name: '腹泻', detail: '伴随发热37.5℃以下')
Symptom.create(name: '腹泻', detail: '伴随皮疹')
Symptom.create(name: '腹泻', detail: '精神反应弱')
Symptom.create(name: '腹泻', detail: '大便蛋花汤状')
Symptom.create(name: '腹泻', detail: '每日大便3次以上')
Symptom.create(name: '腹泻', detail: '伴随发热39℃以上')
Symptom.create(name: '腹泻', detail: '大便稀水状')
Symptom.create(name: '腹泻', detail: '腹泻至今2～3天')
Symptom.create(name: '腹泻', detail: '小便情况明显减少')
Symptom.create(name: '腹泻', detail: '伴随发热37.5℃～39℃')




Symptom.create(name: '皮疹', detail: '全身布满')
Symptom.create(name: '皮疹', detail: '面部')
Symptom.create(name: '皮疹', detail: '皮肤脱屑')
Symptom.create(name: '皮疹', detail: '2周内曾接种过疫苗')
Symptom.create(name: '皮疹', detail: '以前出现过相似皮疹')
Symptom.create(name: '皮疹', detail: '出现在躯干')
Symptom.create(name: '皮疹', detail: '斑丘疹')
Symptom.create(name: '皮疹', detail: '伴随发热37.5℃～39℃')
Symptom.create(name: '皮疹', detail: '伴随发热37.5℃以下')
Symptom.create(name: '皮疹', detail: '皮疹至今2~3天')
Symptom.create(name: '皮疹', detail: '有痒感')
Symptom.create(name: '皮疹', detail: '伴随发热39℃以上')
Symptom.create(name: '皮疹', detail: '皮疹至今1天')


Symptom.create(name: '流涕', detail: '流涕大于4天')
Symptom.create(name: '流涕', detail: '连续流涕')
Symptom.create(name: '流涕', detail: '流涕2~3天')
Symptom.create(name: '流涕', detail: '鼻塞')
Symptom.create(name: '流涕', detail: '清鼻涕')
Symptom.create(name: '流涕', detail: '间歇性流涕')
Symptom.create(name: '流涕', detail: '脓鼻涕')
Symptom.create(name: '流涕', detail: '伴随打喷嚏')
Symptom.create(name: '流涕', detail: '流涕小于24小时')

Symptom.create(name: '辅食', detail: '补锌')
Symptom.create(name: '辅食', detail: '补钙')
Symptom.create(name: '辅食', detail: '厌食')
Symptom.create(name: '辅食', detail: '补AD')
Symptom.create(name: '辅食', detail: '补铁')


Symptom.create(name: '呕吐', detail: '小于24小时')
Symptom.create(name: '呕吐', detail: '大于3天')
Symptom.create(name: '呕吐', detail: '2至3天')
Symptom.create(name: '呕吐', detail: '食欲较差')
Symptom.create(name: '呕吐', detail: '每天1~2次')
Symptom.create(name: '呕吐', detail: '吐奶瓣')
Symptom.create(name: '呕吐', detail: '吐奶')
Symptom.create(name: '呕吐', detail: '吐胃内内容物')
Symptom.create(name: '呕吐', detail: '每天3~4次')
Symptom.create(name: '呕吐', detail: '宿食')
Symptom.create(name: '呕吐', detail: '每天5次以上')

Symptom.create(name: '便秘', detail: '小于3天')
Symptom.create(name: '便秘', detail: '食欲较差')
Symptom.create(name: '便秘', detail: '经常伴随哭闹')
Symptom.create(name: '便秘', detail: '体重增长缓慢')
Symptom.create(name: '便秘', detail: '大于10天')
Symptom.create(name: '便秘', detail: '5~10天')
Symptom.create(name: '便秘', detail: '大便松软')
Symptom.create(name: '便秘', detail: '大便呈黄色')
Symptom.create(name: '便秘', detail: '精神状态差')
Symptom.create(name: '便秘', detail: '大便粘稠')
Symptom.create(name: '便秘', detail: '4~7天')
Symptom.create(name: '便秘', detail: '腹胀')
Symptom.create(name: '便秘', detail: '大便呈黑色')
Symptom.create(name: '便秘', detail: '大便呈绿色')


Symptom.create(name: '发热', detail: '低于37.5℃')
Symptom.create(name: '发热', detail: '喉咙有红、肿、痛')
Symptom.create(name: '发热', detail: '持续72小时以上')
Symptom.create(name: '发热', detail: '精神/食欲差')
Symptom.create(name: '发热', detail: '37.5℃～39℃')
Symptom.create(name: '发热', detail: '高于39℃')
Symptom.create(name: '发热', detail: '持续不到48小时')
Symptom.create(name: '发热', detail: '持续不到48~72小时')


Symptom.create(name: '其他', detail: '眼角分泌物')
Symptom.create(name: '其他', detail: '鼻腔分泌物')
Symptom.create(name: '其他', detail: '结膜炎')
Symptom.create(name: '其他', detail: '口腔溃疡')
