---
JavaScript: true
Ruby: true

engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  tailor:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - css
      - scss
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- node_modules/
- spec/
- vendor/
