# ActionCable.server.broadcast from the console
# https://stackoverflow.com/questions/35176934/actioncable-server-broadcast-from-the-console

redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development: *redis

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: fusion_admin_production
