# ActionCable.server.broadcast from the console
# https://stackoverflow.com/questions/35176934/actioncable-server-broadcast-from-the-console

redis: &redis
  adapter: redis
  url: <%= Settings.redis.server_url %>

development: *redis

test:
  adapter: async

production:
  adapter: redis
  url: <%= Settings.redis.server_url %>
  channel_prefix: production
