# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3939883ccfd90c8031f2e4f9ca9f809b5b2af56f30d9c6a511c205f33304b55ef8c49f30288fdad68caa5e2aba8f1e93d289fde35e314d0bf35cedace1d68573

test:
  secret_key_base: f9331387a89941a5ee74461951199daa4acb5d32767d07f1a2b7ca7fc28c13e004358a2bde18a6219737fb1695c4745a17da2eb31f3e0bba6bf86e9bf6949283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
