qiniu:
  access_key: "4ZphZ7CCpJmmeTl3JltPd0AUSwXFlZR4L5EcX4xi"
  secret_key: "Z7m2P3-VJJOLGDrdEzSvtqCaI1ihumJbOLg-R2ls"
  bucket: "babycare"
  bucket_domain: "7xrod3.com1.z0.glb.clouddn.com"

ronglian:
  SoftVersion: "2013-12-26"
  AccountSid: "8a216da85600ef240156029396a2034d"
  AccountAuthToken: "018d28d0eb364ebd8a103e3dc2702ceb"
  subAccountSid: "05a5f0ab4fdc11e6bb9bac853d9f54f2"
  subAccountAuthToken: "67ca5a784999ad54086ce2af7581fd0d"
  appid: "8a216da85600ef240156029397070353"

im:
  appkey: "3bb9a04dc51d954e8c95d81dc318e335"
  appsecret: "1d3b0a062a8f"

sms_templates:
  captcha: 206219
  notify_all_when_new_reservation: 121703
  notify_user_when_reserved: 121704
  notify_user_when_prepaid: 121708
  notify_doctor_when_prepaid: 121706
  notify_user_when_diagnosed: 121709
  notify_doctor_when_paid: 121710

redis:
  server_url: <%= ENV['REDIS_SERVER_URL'] %>

rollbar:
  access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>

devise:
  secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

doctors:
  good_ats:
    - 儿童外科
    - 儿童耳鼻喉
    - 儿童眼科
    - 儿童神经
    - 儿童心血管
    - 儿童内分泌
    - 儿童血液
    - 儿童消化
    - 儿童呼吸
    - 儿童保健
