# https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index
# 这个是测试号的 app_id
# 用户同意授权，获取code 本地用测试号测试的时候必须用此测试号的app_id
# https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842&token=&lang=zh_CN
# 不然不能跳转 /users/sign_in/?code=CODE

# wx.config 的时候 signature 必须要用生成jsapi_ticket 一样的 app_id
# 微信支付也是


# 本地development环境下不能调试支付

# 公众平台测试号
# https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index
mp:
  app_id: wxffecc41acd70ccd6
  app_secret: 8c76b7677de43e5ba1db3822c7343553
  token: yibutianxia
  redirect_uri: http://babycare.natapp1.cc/wechat/auth_callback

# 开放平台网站应用
open_web:
  app_id: wx5009648228f277ec
  app_secret: fea287de8325e180ffcc8f6b35e29d1d
  redirect_uri: http://babycare.natapp1.cc/wechat/auth_callback
  state: bjk

common:
  domain_name: 'http://babycare.natapp1.cc'

wx_pay:
  app_id: wxfa3c7a8dc6ad872d
  # app_secret: '259f46cfadecd6e2a171b10362f155bd'
  # partner_id: '1368072702'
  # partner_key: 'k9RrfNLZtOx5GghfPJc3tOYXGVr68qpu'
  mch_id: '1484169922'
  api_key: 05ec7b4ee97646f5bae71b229cdab366
  payment_notify_url: "http://wx.yhuan.cc/wx/payment_notify"
  # JSSDK 支付的时候单为分
  # 企业付款金额单位为分, 但是最小支付单位必须1元
  # 这里的单位是元
  prepay_amount: 0.01
  pay_amount: 0.01
