mp:
  app_id: wxfa3c7a8dc6ad872d
  app_secret: d20017912cc6a5977bf283ab58ffe409
  token: bjk_staging


wx_pay:
  app_id: wxfa3c7a8dc6ad872d
  # app_secret: '259f46cfadecd6e2a171b10362f155bd'
  # partner_id: '1368072702'
  # partner_key: 'k9RrfNLZtOx5GghfPJc3tOYXGVr68qpu'
  mch_id: '1484169922'
  api_key: 05ec7b4ee97646f5bae71b229cdab366
  payment_notify_url: "http://wx.yhuan.cc/wx/payment_notify"
  # JSSDK 支付的时候单为分
  # 企业付款金额单位为分, 但是最小支付单位必须1元
  # 这里的单位是元
  prepay_amount: 0.01
  pay_amount: 0.01


# 开放平台网站应用
open_web:
  app_id: wx5009648228f277ec
  app_secret: fea287de8325e180ffcc8f6b35e29d1d
  token: baojiankang

ronglian:
  SoftVersion: "2013-12-26"
  AccountSid: "8a216da85600ef240156029396a2034d"
  AccountAuthToken: "018d28d0eb364ebd8a103e3dc2702ceb"
  subAccountSid: "05a5f0ab4fdc11e6bb9bac853d9f54f2"
  subAccountAuthToken: "67ca5a784999ad54086ce2af7581fd0d"
  appid: "8a216da85600ef240156029397070353"

redis:
  server_url: <%= ENV['REDIS_SERVER_URL'] %>

common:
  domain_name: 'http://wx.yhuan.cc'
