weixin:
  app_id: wxfa3c7a8dc6ad872d
  app_secret: abfe46bde1a4054bc656e92ffafd0a82
  token: yibutianxia

weixin_jssdk:
  app_id: wxfa3c7a8dc6ad872d
  app_secret: abfe46bde1a4054bc656e92ffafd0a82
  token: yibutianxia

qingmayun:
  SoftVersion: "20141029"
  sid: "38f3b667945d4783b937e10158bb9d3b"
  token: "3e31b1fb36b3428082a3cffc13cacf4b"

wx_pay:
  app_id: wxfa3c7a8dc6ad872d
  # app_secret: '259f46cfadecd6e2a171b10362f155bd'
  # partner_id: '1368072702'
  # partner_key: 'k9RrfNLZtOx5GghfPJc3tOYXGVr68qpu'
  mch_id: '1484169922'
  api_key: 05ec7b4ee97646f5bae71b229cdab366
  payment_notify_url: "http://wx.yhuan.cc/wx/payment_notify"
  # JSSDK 支付的时候单为分
  # 企业付款金额单位为分, 但是最小支付单位必须1元
  # 这里的单位是元
  prepay_amount: 0.01
  pay_amount: 0.01

wx_qrcode:
  qrcode_url: "https://www.yhuan.cc/"


common:
  domain_name: 'http://yhuan.cc'